CREATE TABLE catalog_object (
    norad_cat_id INT UNSIGNED NOT NULL,
    object_name VARCHAR(64) NULL,
    object_name_cut BOOLEAN NOT NULL,
    object_id TEXT NULL,
    epoch DATETIME(6) NOT NULL,
    epoch_text VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    mean_motion DOUBLE NOT NULL,
    eccentricity DOUBLE NOT NULL,
    inclination DOUBLE NOT NULL,
    ra_of_asc_node DOUBLE NOT NULL,
    arg_of_pericenter DOUBLE NOT NULL,
    mean_anomaly DOUBLE NOT NULL,
    bstar DOUBLE NOT NULL,
    mean_motion_dot DOUBLE NOT NULL,
    mean_motion_ddot DOUBLE NOT NULL,
    ephemeris_type INT NOT NULL,
    classification_type TEXT NOT NULL,
    element_set_no SMALLINT UNSIGNED NOT NULL,
    rev_at_epoch BIGINT UNSIGNED NOT NULL,
    fetched_at DATETIME(6) NOT NULL,
    source_url TEXT NOT NULL,
    first_fetched_at DATETIME(6) NOT NULL,
    last_fetched_at DATETIME(6) NOT NULL,
    PRIMARY KEY (norad_cat_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
