CREATE TABLE space_weather_event (
    alert_seq BIGINT UNSIGNED NOT NULL,
    rules_version INT UNSIGNED NOT NULL,
    scale CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    satellite INT NULL,
    product VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    state VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    derived_level TINYINT UNSIGNED NULL,
    derived_label VARCHAR(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    previous_state VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    previous_derived_level TINYINT UNSIGNED NULL,
    trigger_kind VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    derived_from TEXT NOT NULL,
    estimated BOOLEAN NOT NULL,
    band VARCHAR(32) NULL,
    channel VARCHAR(32) NULL,
    unit VARCHAR(16) NOT NULL,
    value DOUBLE NULL,
    xray_class VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    time_tag VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    interval_start DATETIME(6) NULL,
    interval_end DATETIME(6) NULL,
    sample_time DATETIME(6) NULL,
    averaging_period_s INT NULL,
    fetched_at DATETIME(6) NULL,
    source_url TEXT NULL,
    freshness_reference DATETIME(6) NULL,
    timer_refresh_at DATETIME(6) NULL,
    no_data_reason VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    no_data_since DATETIME(6) NULL,
    restated_by_time_tag DATETIME(6) NULL,
    ended_by_satellite INT NULL,
    PRIMARY KEY (alert_seq),
    KEY ix_space_weather_event_interval (scale, satellite, interval_start, alert_seq),
    KEY ix_space_weather_event_sample (scale, satellite, sample_time, alert_seq),
    KEY ix_space_weather_event_scale (scale, alert_seq),
    CONSTRAINT fk_space_weather_event_alert FOREIGN KEY (alert_seq) REFERENCES alert_event (alert_seq),
    CONSTRAINT ck_space_weather_event_scale CHECK (scale IN ('G', 'R', 'S')),
    CONSTRAINT ck_space_weather_event_product CHECK (product IN ('swpc.kp', 'swpc.goes.xrays', 'swpc.goes.protons')),
    CONSTRAINT ck_space_weather_event_state CHECK (state IN ('level', 'none', 'no_data', 'ended')),
    CONSTRAINT ck_space_weather_event_previous_state CHECK (previous_state IN ('level', 'none', 'no_data', 'ended')),
    CONSTRAINT ck_space_weather_event_level CHECK (derived_level BETWEEN 1 AND 5),
    CONSTRAINT ck_space_weather_event_previous_level CHECK (previous_derived_level BETWEEN 1 AND 5),
    CONSTRAINT ck_space_weather_event_trigger CHECK (trigger_kind IN ('level_change', 'revision', 'restatement', 'refresh')),
    CONSTRAINT ck_space_weather_event_no_data_reason CHECK (no_data_reason IN ('rejected', 'zero_run_edge', 'age_limit'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
