CREATE TABLE space_weather_series (
    scale CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    series_satellite INT NOT NULL,
    rules_version INT UNSIGNED NOT NULL,
    state VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    derived_level TINYINT UNSIGNED NULL,
    derived_label VARCHAR(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    value DOUBLE NULL,
    unit VARCHAR(16) NOT NULL,
    xray_class VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    time_tag VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    interval_start DATETIME(6) NULL,
    sample_time DATETIME(6) NULL,
    no_data_reason VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NULL,
    no_data_since DATETIME(6) NULL,
    ended_by_satellite INT NULL,
    freshness_reference DATETIME(6) NULL,
    state_alert_seq BIGINT UNSIGNED NOT NULL,
    last_alert_seq BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (scale, series_satellite),
    CONSTRAINT ck_space_weather_series_scale CHECK (scale IN ('G', 'R', 'S')),
    CONSTRAINT ck_space_weather_series_state CHECK (state IN ('level', 'none', 'no_data', 'ended')),
    CONSTRAINT ck_space_weather_series_level CHECK (derived_level BETWEEN 1 AND 5),
    CONSTRAINT ck_space_weather_series_no_data_reason CHECK (no_data_reason IN ('rejected', 'zero_run_edge', 'age_limit'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
