CREATE TABLE screening_run (
    alert_seq BIGINT UNSIGNED NOT NULL,
    rules_version INT UNSIGNED NOT NULL,
    run_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    window_start DATETIME(6) NOT NULL,
    window_end DATETIME(6) NOT NULL,
    input_fetched_at DATETIME(6) NOT NULL,
    report_distance_m DOUBLE NOT NULL,
    watchlist_accepted INT UNSIGNED NOT NULL,
    catalog_admitted INT UNSIGNED NOT NULL,
    pairs INT UNSIGNED NOT NULL,
    pairs_not_screenable INT UNSIGNED NOT NULL,
    pairs_removed_by_prefilter INT UNSIGNED NOT NULL,
    pairs_searched INT UNSIGNED NOT NULL,
    approach_count INT UNSIGNED NOT NULL,
    omitted_approach_event_ids INT UNSIGNED NULL,
    omitted_suppressed INT UNSIGNED NULL,
    omitted_rejected INT UNSIGNED NULL,
    omitted_not_screened INT UNSIGNED NULL,
    omitted_epoch_after_start INT UNSIGNED NULL,
    omitted_differing_copies INT UNSIGNED NULL,
    omitted_differing_copies_over_cap INT UNSIGNED NULL,
    PRIMARY KEY (alert_seq),
    UNIQUE KEY uk_screening_run_run_id (run_id),
    KEY ix_screening_run_window (window_start, rules_version),
    CONSTRAINT fk_screening_run_alert FOREIGN KEY (alert_seq) REFERENCES alert_event (alert_seq)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
